#!/bin/bash

this=`basename $0`
command=`basename $1`

processes=`ps -efww | grep $command | grep -v $this | grep -v grep`

if ! [ "$processes" ] ; then

	echo starting $@
	$@ &
else
	echo $processes
	echo already running
fi
