#!/bin/bash

dbs=$@
if [ -f $1 ] ; then
	dbs=`cat $1`
fi

for db in $dbs ; do
	/usr/bin/docker run -v "/srv/data:/srv/mrs-data/raw" -v "/srv/mrs:/srv/mrs-data/mrs" -it mrs_mrs ./mrs build $db > /srv/data/status/$db.mrs_log
done
